# Generated by Django 5.0 on 2024-01-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='enrolled',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='group',
            name='queue',
            field=models.CharField(default='0'),
        ),
    ]
